Repository Wallet-expedition/MODIMOA, pull requests merged in 2022-03, with the labels that each got.

#118 장바구니 구매창 연동 작업
  frontend/src/Components/MyBag/BagProduct.js
  frontend/src/Components/MyBag/BagProductList.js
  frontend/src/Components/MyBag/BuyModal/BuyModalContainer.js
  frontend/src/Components/MyBag/BuyModal/BuyModalPresenter.js
  frontend/src/Components/MyBag/MyBagContainer.js
  frontend/src/Components/MyBag/MyBagPresenter.js
  frontend/src/Components/MyBag/PurchasedBagProduct.js
  frontend/src/Components/Util/AddComma.js
  frontend/src/Components/Util/Constant.js
  frontend/src/Components/Util/GetUpdatedNextList.js
  frontend/src/Components/Util/SampleList.js
  frontend/src/Components/Util/useSetMyBagList.js
  frontend/src/Pages/MyBagPage.js
  frontend/src/scss/components/_buyModal.scss
  frontend/src/scss/components/_myBagProduct.scss
Labels: :sun_with_face: FE, :hammer_and_wrench: Refactor

#119 (Desktop) 상품 리스트 페이지 추가 작업
  frontend/src/Components/Header/HeaderPresenter.js
  frontend/src/Components/Layout/LayoutPresenter.js
  frontend/src/Components/Layout/SideMenu/SideMenuContainer.js
  frontend/src/Components/Layout/SideMenu/SideMenuPresenter.js
  frontend/src/Pages/ProductListPage.js
  frontend/src/scss/Layout.scss
  frontend/src/scss/ProductList.scss
  frontend/src/scss/components/_martList.scss
  frontend/src/scss/components/_product.scss
  frontend/src/scss/components/_search.scss
  frontend/src/scss/components/_sideMenu.scss
  frontend/src/scss/components/_sideMenuBtn.scss
Labels: :sun_with_face: FE, :art: Design

#120 [Fix] css 지정자 변경
  frontend/src/scss/components/_product.scss
Labels: :sun_with_face: FE

#121 (Desktop) 간단한 레이아웃 수정 및 장바구니 이슈 해결
  frontend/src/Components/About/AboutContainer.js
  frontend/src/Components/Clock/ClockContainer.js
  frontend/src/Components/Header/HeaderPresenter.js
  frontend/src/Components/Intro/IntroContainer.js
  frontend/src/Components/Intro/IntroPresenter.js
  frontend/src/Components/Layout/BackButton/BackButtonContainer.js
  frontend/src/Components/Layout/BackButton/BackButtonPresenter.js
  frontend/src/Components/Layout/LayoutContainer.js
  frontend/src/Components/Layout/SideMenu/SideMenuContainer.js
  frontend/src/Components/Layout/SideMenu/SideMenuPresenter.js
  frontend/src/Components/Layout/SideMenuBtn/SideMenuBtnContainer.js
  frontend/src/Components/Layout/SideMenuBtn/SideMenuBtnPresenter.js
  frontend/src/Components/Loading/LoadingPresenter.js
  frontend/src/Components/Login/LoginButton/FacebookLoginButton.js
  frontend/src/Components/Login/LoginButton/GoogleLoginButton.js
  frontend/src/Components/Login/LoginButton/KaKaoLoginButton.js
  frontend/src/Components/Login/LoginContainer.js
  frontend/src/Components/Login/LoginPresenter.js
  frontend/src/Components/LogoutToastMessage/Presenter.js
  frontend/src/Components/Main/MainContainer.js
  frontend/src/Components/Main/MainPresenter.js
  frontend/src/Components/MartList/MartListBtn/MartListBtnContainer.js
  frontend/src/Components/MartList/MartListContainer.js
  frontend/src/Components/MartList/MartListPresenter.js
  frontend/src/Components/MyBag/BagProduct.js
  frontend/src/Components/MyBag/BuyModal/BuyModalContainer.js
  frontend/src/Components/MyBag/BuyModal/BuyModalPresenter.js
  frontend/src/Components/MyBag/MyBagContainer.js
  frontend/src/Components/MyBag/MyBagPresenter.js
  frontend/src/Components/MyPageContent/MyPageContainer.js
  frontend/src/Components/MyPageContent/MyPagePresenter.js
  frontend/src/Components/Product/ProductContainer.js
  frontend/src/Components/Product/ProductPresenter.js
  frontend/src/Components/ProductDetail/ProductDetailContainer.js
  frontend/src/Components/ProductDetail/ProductDetailPresenter.js
  frontend/src/Components/ProductList/ProductListContainer.js
  frontend/src/Components/ProductList/ProductListPresenter.js
  frontend/src/Components/Register/RegisterButton/FacebookRegisterButton.js
  frontend/src/Components/Register/RegisterButton/GoogleRegisterButton.js
  frontend/src/Components/Register/RegisterButton/KaKaoRegisterButton.js
  frontend/src/Components/Register/RegisterContainer.js
  frontend/src/Components/Register/RegisterPresenter.js
  frontend/src/Pages/AboutPage.js
  frontend/src/Pages/IntroPage.js
  frontend/src/Pages/LoginPage.js
  frontend/src/Pages/MainPage.js
  frontend/src/Pages/MyBagPage.js
  frontend/src/Pages/MyPage.js
  frontend/src/Pages/ProductDetailPage.js
  frontend/src/Pages/ProductListPage.js
  frontend/src/Pages/RegisterPage.js
  frontend/src/Routes/Router.js
  frontend/src/scss/components/_detail.scss
  frontend/src/scss/components/_headerLogo.scss
  frontend/src/scss/components/_myBagProduct.scss
  frontend/src/scss/components/_myPage.scss
Labels: :sun_with_face: FE, :art: Design, :hammer_and_wrench: Refactor

#122 [Fix][Feat] 상품 이미지 깨지는 것 해결 + 레이아웃 수정
  frontend/src/Components/ProductList/ProductListPresenter.js
  frontend/src/scss/Layout.scss
  frontend/src/scss/ProductList.scss
  frontend/src/scss/components/_product.scss
Labels: :sun_with_face: FE, :art: Design

#124 [Refactor] 인피니티스크롤 모듈화 및 간단한 레이아웃
  frontend/src/Components/Hook/useInfiniteScroll.js
  frontend/src/Components/Hook/useLoadData.js
  frontend/src/Components/Hook/useSetMyBagList.js
  frontend/src/Components/Layout/SideMenu/SideMenuPresenter.js
  frontend/src/Components/MyBag/BuyModal/BuyModalContainer.js
  frontend/src/Components/ProductList/ProductListContainer.js
  frontend/src/Components/ProductList/ProductListPresenter.js
  frontend/src/Components/Util/Constant.js
  frontend/src/Pages/MyBagPage.js
  frontend/src/scss/ProductList.scss
  frontend/src/scss/components/_detail.scss
Labels: :sun_with_face: FE, :hammer_and_wrench: Refactor

#126 Auth 유틸 작동
  frontend/src/Components/Layout/SideMenu/SideMenuContainer.js
  frontend/src/Components/Layout/SideMenu/SideMenuPresenter.js
  frontend/src/Components/MyPageContent/MyPageContainer.js
  frontend/src/Components/Util/Auth.js
  frontend/src/Routes/Router.js
  frontend/src/Store/Actions/userAction.js
Labels: :sun_with_face: FE, :hammer_and_wrench: Refactor

#127 상품 리스트 페이지 UX 개선
  frontend/src/Components/Layout/LayoutContainer.js
  frontend/src/Components/Layout/SideMenuBtn/SideMenuBtnContainer.js
  frontend/src/scss/ProductList.scss
Labels: :sun_with_face: FE, :hammer_and_wrench: Refactor

#128 장바구니 레이아웃 다루기, NoDataComponent 적용
  .DS_Store
  frontend/public/img/no_data.png
  frontend/src/Components/HelmetComponent/HelmetPresenter.js
  frontend/src/Components/Layout/LayoutContainer.js
  frontend/src/Components/Layout/SideMenu/SideMenuContainer.js
  frontend/src/Components/Layout/SideMenuBtn/SideMenuBtnContainer.js
  frontend/src/Components/Layout/SideMenuBtn/SideMenuBtnPresenter.js
  frontend/src/Components/Login/LoginButton/LoginButton.js
  frontend/src/Components/Login/LoginPresenter.js
  frontend/src/Components/Main/MainContainer.js
  frontend/src/Components/Main/MainPresenter.js
  frontend/src/Components/MartList/MartListBtn/MartListBtnContainer.js
  frontend/src/Components/MartList/MartListContainer.js
  frontend/src/Components/MartList/MartListPresenter.js
  frontend/src/Components/MyBag/BagDescription.js
  frontend/src/Components/MyBag/BagProduct.js
  frontend/src/Components/MyBag/BagProductList.js
  frontend/src/Components/MyBag/BuyModal/BuyModalContainer.js
  frontend/src/Components/MyBag/BuyModal/BuyModalPresenter.js
  frontend/src/Components/MyBag/MyBagContainer.js
  frontend/src/Components/MyBag/MyBagPresenter.js
  frontend/src/Components/MyPageContent/MyPageContainer.js
  frontend/src/Components/MyPageContent/MyPagePresenter.js
  frontend/src/Components/NoData/NoDataContainer.js
  frontend/src/Components/NoData/NoDataPresenter.js
  frontend/src/Components/NoData/index.js
  frontend/src/Components/Product/ProductPresenter.js
  frontend/src/Components/ProductDetail/ProductDetailPresenter.js
  frontend/src/Components/ProductList/ProductListContainer.js
  frontend/src/Components/ProductList/ProductListPresenter.js
  frontend/src/Components/Register/RegisterButton/RegisterButton.js
  frontend/src/Components/Register/RegisterPresenter.js
  frontend/src/Hook/useInfiniteScroll.js
  frontend/src/Hook/useLoadData.js
  frontend/src/Hook/useSetMyBagList.js
  frontend/src/Pages/MyBagPage.js
  frontend/src/Routes/Router.js
  frontend/src/Store/Actions/productAction.js
  frontend/src/Store/Actions/userAction.js
  frontend/src/Store/Reducers/sideMenuReducer.js
  frontend/src/Util/AddComma.js
  frontend/src/Util/Auth.js
  frontend/src/Util/Constant.js
  frontend/src/Util/Cookie.js
  frontend/src/Util/DetectMobile.js
  frontend/src/Util/GetUpdatedNextList.js
  frontend/src/Util/Request.js
  frontend/src/Util/SampleList.js
  frontend/src/Util/Throttle.js
  frontend/src/scss/Layout.scss
  frontend/src/scss/ProductList.scss
  frontend/src/scss/components/_myBag.scss
  frontend/src/scss/components/_myBagProduct.scss
  frontend/src/scss/components/_noData.scss
Labels: :sun_with_face: FE, :art: Design, :hammer_and_wrench: Refactor
