Repository Wallet-expedition/MODIMOA, pull requests merged in 2022-01, with the labels that each got.

#79 Desktop 메인 페이지 레이아웃 수정
  frontend/src/scss/Layout.scss
  frontend/src/scss/components/_mainContent.scss
  frontend/src/scss/components/_search.scss
Labels: :sun_with_face: FE, :art: Design

#84 자동 배포 시 .env 작성
  .github/workflows/main.yml
Labels: :sun_with_face: FE, :rocket: DevOps

#85 .env 생성 시점 변경
  .github/workflows/main.yml
Labels: :sun_with_face: FE, :rocket: DevOps

#86 dotenv.config 시점 변경
  frontend/src/App.js
Labels: :sun_with_face: FE, :rocket: DevOps

#87 dotenv.config() 시점 변경2
  frontend/src/App.js
  frontend/src/index.js
Labels: :sun_with_face: FE, :rocket: DevOps

#88 main.yml에 Setup Node 추가
  .github/workflows/main.yml
Labels: :sun_with_face: FE, :rocket: DevOps

#89 [Chore] 어쩌면 따옴표에게 잘못이 있을지도
  .github/workflows/main.yml
Labels: :sun_with_face: FE, :rocket: DevOps

#90 어쩌면 지금까지 위치가 달랐나
  .github/workflows/main.yml
Labels: :sun_with_face: FE, :rocket: DevOps

#91 배포 스크립트 최종 수정
  .github/workflows/main.yml
Labels: :sun_with_face: FE, :rocket: DevOps

#96 취약점 일부 해결
  frontend/package.json
  frontend/src/index.js
  frontend/yarn.lock
Labels: :sun_with_face: FE, :hammer_and_wrench: Refactor

#94 장바구니 삭제기능 & Axios 관리 & API URL
  frontend/public/img/gear.png
  frontend/src/Components/BuyModal/BuyModalContainer.js
  frontend/src/Components/Layout/SideMenu/SideMenuContainer.js
  frontend/src/Components/MyBag/BagDescription.js
  frontend/src/Components/MyBag/BagProduct.js
  frontend/src/Components/MyBag/BagProductList.js
  frontend/src/Components/MyBag/MyBagContainer.js
  frontend/src/Components/MyBag/MyBagPresenter.js
  frontend/src/Components/MyPageContent/MyPageContainer.js
  frontend/src/Components/Register/RegisterButton/KaKaoRegisterButton.js
  frontend/src/Components/Util/Request.js
  frontend/src/Pages/MyBagPage.js
  frontend/src/Store/Actions/productAction.js
  frontend/src/Store/Actions/type.js
  frontend/src/Store/Actions/userAction.js
  frontend/src/Store/Reducers/productReducer.js
  frontend/src/scss/MyBagPage.scss
  frontend/src/scss/components/_product.scss
  frontend/src/scss/components/_sortbar.scss
  frontend/yarn.lock
Labels: :sun_with_face: FE, :hammer_and_wrench: Refactor

#98 모달 디자인 변경 및 장바구니 로직 작성
  frontend/src/Components/BuyModal/BuyModalPresenter.js
  frontend/src/Components/MyBag/BuyModal/BuyModalContainer.js
  frontend/src/Components/MyBag/BuyModal/BuyModalPresenter.js
  frontend/src/Components/MyBag/BuyModal/index.js
  frontend/src/Components/MyBag/MyBagContainer.js
  frontend/src/Components/MyBag/MyBagPresenter.js
  frontend/src/Components/ProductDetail/ProductDetailContainer.js
  frontend/src/Components/Util/Request.js
  frontend/src/Store/Actions/productAction.js
  frontend/src/Store/Actions/type.js
  frontend/src/Store/Reducers/productReducer.js
  frontend/src/scss/MyBagPage.scss
  frontend/src/scss/components/_buyModal.scss
  frontend/src/scss/components/_myBag.scss
Labels: :sun_with_face: FE, :art: Design, :hammer_and_wrench: Refactor

#99 scss color 변수 적용
  frontend/src/scss/Layout.scss
  frontend/src/scss/base/_variable.scss
  frontend/src/scss/components/_about.scss
  frontend/src/scss/components/_buyModal.scss
  frontend/src/scss/components/_detail.scss
  frontend/src/scss/components/_intro.scss
  frontend/src/scss/components/_login.scss
  frontend/src/scss/components/_logoutToast.scss
  frontend/src/scss/components/_mainContent.scss
  frontend/src/scss/components/_martLabel.scss
  frontend/src/scss/components/_martList.scss
  frontend/src/scss/components/_myBag.scss
  frontend/src/scss/components/_myPage.scss
  frontend/src/scss/components/_product.scss
  frontend/src/scss/components/_search.scss
  frontend/src/scss/components/_sideMenu.scss
  frontend/src/scss/components/_sideMenuBtn.scss
  frontend/src/scss/components/_sortbar.scss
Labels: :sun_with_face: FE, :art: Design, :hammer_and_wrench: Refactor

#100 상품 리스트 API 변경
  frontend/src/Store/Actions/productAction.js
Labels: :sun_with_face: FE, :hammer_and_wrench: Refactor

#102 맞지 않는 레이아웃 수정, 뒤로 가기 버튼 리팩토링
  frontend/src/App.js
  frontend/src/Components/Layout/LayoutContainer.js
  frontend/src/Components/Layout/LayoutPresenter.js
  frontend/src/Components/Layout/SideMenuBtn/SideMenuBtnContainer.js
  frontend/src/Components/MartList/MartListBtn/MartListBtnContainer.js
  frontend/src/Components/Util/DetectMobile.js
  frontend/src/Routes/Router.js
  frontend/src/scss/Layout.scss
  frontend/src/scss/components/_intro.scss
  frontend/src/scss/components/_sideMenu.scss
  frontend/src/scss/components/_sideMenuBtn.scss
Labels: :sun_with_face: FE, :art: Design, :hammer_and_wrench: Refactor

#101 장바구니 로직 수정 및 API 수정
  frontend/src/Components/MyBag/BagProductList.js
  frontend/src/Components/MyBag/BuyModal/BuyModalContainer.js
  frontend/src/Components/MyBag/MyBagContainer.js
  frontend/src/Components/MyBag/MyBagPresenter.js
  frontend/src/Components/MyBag/PurchasedBagProduct.js
  frontend/src/Components/MyBag/WishBagProduct.js
  frontend/src/Components/MyPageContent/MyPagePresenter.js
  frontend/src/Components/Product/ProductPresenter.js
  frontend/src/Components/ProductDetail/ProductDetailPresenter.js
  frontend/src/Components/ProductList/ProductListContainer.js
  frontend/src/Components/Register/RegisterButton/FacebookRegisterButton.js
  frontend/src/Components/Register/RegisterButton/GoogleRegisterButton.js
  frontend/src/Components/Register/RegisterButton/KaKaoRegisterButton.js
  frontend/src/Components/Util/AddComma.js
  frontend/src/Components/Util/Constant.js
  frontend/src/Components/Util/Request.js
  frontend/src/Components/Util/useSetMyBagList.js
  frontend/src/Pages/MyBagPage.js
  frontend/src/Store/Actions/productAction.js
  frontend/src/Store/Actions/userAction.js
Labels: :sun_with_face: FE, :hammer_and_wrench: Refactor

#104 상품 목록 페이지 Desktop ver. 1차
  frontend/src/Components/About/AboutPresenter.js
  frontend/src/Components/Layout/LayoutContainer.js
  frontend/src/Components/Layout/LayoutPresenter.js
  frontend/src/Components/Layout/SideMenuBtn/SideMenuBtnContainer.js
  frontend/src/Components/Layout/SideMenuBtn/SideMenuBtnPresenter.js
  frontend/src/Components/MartList/MartListBtn/MartListBtnContainer.js
  frontend/src/Components/MartList/MartListBtn/MartListBtnPresenter.js
  frontend/src/Components/MartList/MartListContainer.js
  frontend/src/Components/MartList/MartListPresenter.js
  frontend/src/Store/Reducers/sideMenuReducer.js
  frontend/src/scss/ProductList.scss
  frontend/src/scss/components/_martList.scss
  frontend/src/scss/components/_product.scss
  frontend/src/scss/components/_sideMenu.scss
  frontend/src/scss/components/_sideMenuBtn.scss
Labels: :sun_with_face: FE, :art: Design

#105 [BE/BUG] 사용자 탈퇴 기능
  backend/src/main/java/com/modimoa/backend/repository/MybagRepository.java
  backend/src/main/java/com/modimoa/backend/service/MybagService.java
  backend/src/main/java/com/modimoa/backend/service/UserService.java
Labels: :sun_behind_large_cloud: BE

#110 장바구니 productId 호출을 mybagId로 변경
  frontend/src/Components/MyBag/BagProductList.js
  frontend/src/Components/MyBag/MyBagContainer.js
  frontend/src/Components/Util/useSetMyBagList.js
  frontend/src/Store/Actions/productAction.js
Labels: :sun_with_face: FE, :hammer_and_wrench: Refactor
